# Generated by Django 4.1.4 on 2022-12-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Warehouse', models.CharField(max_length=15, null=True)),
                ('Product_Code', models.CharField(max_length=15, unique=True)),
                ('Product_Category', models.IntegerField(unique=True)),
                ('Order_Demand', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=15, unique=True)),
                ('warehouse', models.CharField(max_length=15, null=True)),
                ('predictions', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=15, unique=True)),
                ('warehouse', models.CharField(max_length=15, null=True)),
                ('order', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
